JITB-1: Fixed(?) stale reference edge case(?)
Got a weird exception while waiting for the other players.
I suspect that it was an edge case.
Here's what I think happened.

1. JITB answered Round 1 prompts
2. JITB went into idle _what_page_is_this() mode
3. Inside _is_thrip_prompt_page()...
	- Read page (inside try/except)
	- Fell through to else
	- Page changed
	- Continued checking in else but the page was stale
	- Threw exception

So I moved most of the else logic, as needed, into the try/except blocks
and added the new StaleElementReferenceException exception to all the
_is_*_page() try/except catches.

Here's the output from the crash:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/__main__.py", line 10, in <module>
    sys.exit(main())
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_main.py", line 30, in main
    play_the_game(room_code=room_code, username=username, ai_obj=client)
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_website.py", line 116, in play_the_game
    curr_page = _what_page_is_this(web_driver)
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_website.py", line 525, in _what_page_is_this
    elif _is_thrip_prompt_page(web_driver):
  File "/home/joe/Documents/Personal/Programming/jack-in-the-box/jitb/jitb_website.py", line 381, in _is_thrip_prompt_page
    if temp_we.text.lower().startswith(prompt.lower()):
  File "/home/joe/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
  File "/home/joe/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/joe/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/home/joe/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=118.0.5993.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception

Changes to be committed:
	modified:   jitb/jitb_website.py

Untracked files:
	actual_integration.txt